# Generated by Django 5.2.3 on 2025-07-06 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_id', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='matiere')),
                ('description', models.TextField(max_length=500)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere', to='programmes.niveaux')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(verbose_name='chapitre numero')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='files')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('creer_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='programmes.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.niveaux')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
